Add Swagger documentation
wolox-training/as-java pull request #10
Opened 2021-05-27 17:30 UTC by AndreyWolox

## Summary
- add  swagger dependence
- add swagger documentation
- add swagger config
## Trello Card
https://trello.com/c/nyr7oX0D/40-swagger

2021-05-27 23:29 UTC, leandrocostawolox reviewed
Two minor comments 👼

2021-05-27 23:29 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> +    @ApiResponses(value = {@ApiResponse(code = 200, message = "Successfully created Book")})
201

2021-05-27 23:29 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +    @ApiModelProperty(value = "The gener of the book", example = "Action")
*genre

2021-05-31 15:00 UTC, leandrocostawolox requested changes

2021-05-31 15:00 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +    @ApiModelProperty(value = "The gener of the book", example = "Action")
*genre

2021-05-31 20:57 UTC, CarlosLugo22 approved these changes
Great, the comments made by Lea was worked, Good

2021-06-01 23:01 UTC, leandrocostawolox approved these changes

2021-06-02 01:54 UTC, merged