Add guava validation not null
wolox-training/as-java pull request #11
Opened 2021-05-27 17:52 UTC by AndreyWolox

## Summary
- Add guava precondiction to the setters of the models
- Add guava dependence
## Trello Card
https://trello.com/c/4j3ojn2V/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2021-05-27 23:50 UTC, leandrocostawolox requested changes
Some recommendations about field validations :)

2021-05-27 23:50 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/User.java
> +        this.birthdate = checkNotNull(birthdate, ValidationError.NULL_VALUE.getMsg());
You should check if the birthdate is before now :)

2021-05-27 23:50 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +        this.pages = checkNotNull(pages, ValidationError.NULL_VALUE.getMsg());
The pages shouldn't be null, or 0 either

2021-05-27 23:50 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +        this.subtitle = checkNotNull(subtitle, ValidationError.NULL_VALUE.getMsg());
For Strings it's good to check for null or empty

2021-05-31 20:29 UTC, leandrocostawolox approved these changes

2021-05-31 21:06 UTC, CarlosLugo22 approved these changes
Good, a comment just to have in mind

2021-05-31 21:06 UTC, CarlosLugo22 commented on src/main/java/wolox/training/models/Book.java
> +        this.id = checkNotNull(id, ValidationError.NULL_VALUE.getMsg());
Great, a comment this is one of a lot preconditions, for example for id just be numbers, or if is a email needs to have and special character like '@', or for names not have special characters if they are not needed and for the years or birhdate that the date is in a range or something like that.

2021-05-31 22:51 UTC, merged