Feature book crud controller
wolox-training/as-java pull request #5
Opened 2021-05-26 00:36 UTC by AndreyWolox

## Summary
- add crud methods in book controller class
- add error book enum
## Trello Card
https://trello.com/c/inNSDohk/18-crear-las-operaciones-crud-de-book

2021-05-26 20:05 UTC, leandrocostawolox requested changes
I wrote you some comments to improve this feature :)

2021-05-26 20:05 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> +    private BookRepository repository;
It's better to inject dependencies using the constructor :) It gives us some benefits like testability. You can read more about this [here](https://stackoverflow.com/questions/40620000/spring-autowire-on-properties-vs-constructor/40620318)

2021-05-26 20:05 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/BookController.java
> +    public void delete(@PathVariable Long id) {
When there is no body in the response, instead of using `200` as the HTTP status code, we should return `204`

2021-05-26 20:25 UTC, CarlosLugo22 requested changes

2021-05-26 20:25 UTC, CarlosLugo22 commented on src/main/java/wolox/training/enums/BookError.java
> +    WRONG_ID("Provide correct Book Id"),
maybe you meant "Provide wrong Bok Id" ?

2021-05-27 17:36 UTC, CarlosLugo22 approved these changes, later dismissed

2021-05-27 21:23 UTC, leandrocostawolox approved these changes

2021-05-31 15:16 UTC, merged