Feature user crud controller
wolox-training/as-java pull request #9
Opened 2021-05-26 14:52 UTC by AndreyWolox

## Summary
- Add user crud controller
- Add error user enum
## Trello Card
https://trello.com/c/dAXR5dRU/21-crear-user-controller-con-las-operaciones-crud-de-user

2021-05-26 20:44 UTC, CarlosLugo22 reviewed
Have in mind the comments from Leandro at the other controller

2021-05-26 20:44 UTC, CarlosLugo22 commented on src/main/java/wolox/training/controllers/UserController.java
> +     *
Can add exceptions to documentation like said in the other controller

2021-05-26 20:52 UTC, leandrocostawolox requested changes
Great! Just some minor comments :)

2021-05-26 20:52 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    @GetMapping()
There is no need to add the extra `()`. You can use just the annotation `@GetMapping`

2021-05-26 20:52 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +        userRepository.deleteById(id);
As I commented for the Books controller: `204` will be a better HTTP status code for this endpoint :)

2021-05-26 20:52 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    @PutMapping("/{id}/book/{bookId}")
`.../books/...` As a convention we should use the resources in their plural form

2021-05-26 20:52 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    @DeleteMapping("/{id}/book/{bookId}")
Same here: `books` instead of book

2021-05-27 17:38 UTC, CarlosLugo22 approved these changes

2021-05-27 21:25 UTC, leandrocostawolox approved these changes
Excellent!

2021-05-31 15:18 UTC, merged